export const MENU_ITEM_REQUEST = "MENU_ITEM_REQUEST";
export const MENU_ITEM_SUCCESS = "MENU_ITEM_SUCCESS";
export const MENU_ITEM_FAIL = "MENU_ITEM_FAIL";
export const MENU_ITEM_RESET = "MENU_ITEM_RESET";

export const MENU_CREATE_ITEM_REQUEST = "MENU_CREATE_ITEM_REQUEST";
export const MENU_CREATE_ITEM_SUCCESS = "MENU_CREATE_ITEM_SUCCESS";
export const MENU_CREATE_ITEM_FAIL = "MENU_CREATE_ITEM_FAIL";