import { CART_ADD_ITEM, CART_EMPTY, CART_REMOVE_ITEM, CART_SAVE_PAYMENT_METHOD, CART_SAVE_SHIPPING_ADDRESS } from "../constants/cartConstants";
import { DELETE_MENU_ITEM_FAIL, DELETE_MENU_ITEM_REQUEST, DELETE_MENU_ITEM_SUCCESS, MENU_CREATE_ITEM_FAIL, MENU_CREATE_ITEM_REQUEST, MENU_CREATE_ITEM_SUCCESS, MENU_ITEM_FAIL, MENU_ITEM_REQUEST, MENU_ITEM_RESET, MENU_ITEM_SUCCESS } from "../constants/menuConstants";
import { GET_ORDERS_FAIL, GET_ORDERS_REQUEST, GET_ORDERS_SUCCESS, ORDER_CREATE_FAIL, ORDER_CREATE_REQUEST, ORDER_CREATE_RESET, ORDER_CREATE_SUCCESS, ORDER_DETAILS_FAIL, ORDER_DETAILS_REQUEST, ORDER_DETAILS_SUCCESS, ORDER_PAY_FAIL, ORDER_PAY_REQUEST, ORDER_PAY_RESET, ORDER_PAY_SUCCESS } from "../constants/orderConstants";
import { PRODUCT_DETAILS_FAIL, PRODUCT_DETAILS_REQUEST, PRODUCT_DETAILS_SUCCESS, PRODUCT_LIST_FAIL, PRODUCT_LIST_REQUEST, PRODUCT_LIST_SUCCESS } from "../constants/productConstants";
import { USER_REGISTER_FAIL, USER_REGISTER_REQUEST, USER_REGISTER_SUCCESS, USER_SIGNIN_FAIL, USER_SIGNIN_REQUEST, USER_SIGNIN_SUCCESS, USER_SIGNOUT } from "../constants/userConstants";

describe("Make sure constants are kept the same as their strings", () => {
    test("Card constants", () => {
        expect(CART_ADD_ITEM).toBe("CART_ADD_ITEM");
        expect(CART_REMOVE_ITEM).toBe("CART_REMOVE_ITEM");
        expect(CART_SAVE_SHIPPING_ADDRESS).toBe("CART_SAVE_SHIPPING_ADDRESS");
        expect(CART_SAVE_PAYMENT_METHOD).toBe("CART_SAVE_PAYMENT_METHOD");
        expect(CART_EMPTY).toBe("CART_EMPTY");
    });

    test("Menu constants", () => {
        expect(MENU_ITEM_REQUEST).toBe("MENU_ITEM_REQUEST");
        expect(MENU_ITEM_SUCCESS).toBe("MENU_ITEM_SUCCESS");
        expect(MENU_ITEM_FAIL).toBe("MENU_ITEM_FAIL");
        expect(MENU_ITEM_RESET).toBe("MENU_ITEM_RESET");
        expect(MENU_CREATE_ITEM_REQUEST).toBe("MENU_CREATE_ITEM_REQUEST");
        expect(MENU_CREATE_ITEM_SUCCESS).toBe("MENU_CREATE_ITEM_SUCCESS");
        expect(MENU_CREATE_ITEM_FAIL).toBe("MENU_CREATE_ITEM_FAIL");
        expect(DELETE_MENU_ITEM_REQUEST).toBe("DELETE_MENU_ITEM_REQUEST");
        expect(DELETE_MENU_ITEM_SUCCESS).toBe("DELETE_MENU_ITEM_SUCCESS");
        expect(DELETE_MENU_ITEM_FAIL).toBe("DELETE_MENU_ITEM_FAIL");
    });

    test("Order constants", () => {
        expect(ORDER_CREATE_REQUEST).toBe("ORDER_CREATE_REQUEST");
        expect(ORDER_CREATE_SUCCESS).toBe("ORDER_CREATE_SUCCESS");
        expect(ORDER_CREATE_FAIL).toBe("ORDER_CREATE_FAIL");
        expect(ORDER_CREATE_RESET).toBe("ORDER_CREATE_RESET");
        expect(ORDER_PAY_REQUEST).toBe("ORDER_PAY_REQUEST");
        expect(ORDER_PAY_SUCCESS).toBe("ORDER_PAY_SUCCESS");
        expect(ORDER_PAY_FAIL).toBe("ORDER_PAY_FAIL");
        expect(ORDER_PAY_RESET).toBe("ORDER_PAY_RESET");
        expect(ORDER_DETAILS_REQUEST).toBe("ORDER_DETAILS_REQUEST");
        expect(ORDER_DETAILS_SUCCESS).toBe("ORDER_DETAILS_SUCCESS");
        expect(ORDER_DETAILS_FAIL).toBe("ORDER_DETAILS_FAIL");
        expect(GET_ORDERS_REQUEST).toBe("GET_ORDERS_REQUEST");
        expect(GET_ORDERS_SUCCESS).toBe("GET_ORDERS_SUCCESS");
        expect(GET_ORDERS_FAIL).toBe("GET_ORDERS_FAIL");
    });

    test("Product constants", () => {
        expect(PRODUCT_LIST_REQUEST).toBe("PRODUCT_LIST_REQUEST");
        expect(PRODUCT_LIST_SUCCESS).toBe("PRODUCT_LIST_SUCCESS");
        expect(PRODUCT_LIST_FAIL).toBe("PRODUCT_LIST_FAIL");
        expect(PRODUCT_DETAILS_REQUEST).toBe("PRODUCT_DETAILS_REQUEST");
        expect(PRODUCT_DETAILS_SUCCESS).toBe("PRODUCT_DETAILS_SUCCESS");
        expect(PRODUCT_DETAILS_FAIL).toBe("PRODUCT_DETAILS_FAIL");
    });

    test("User constants", () => {
        expect(USER_SIGNIN_REQUEST).toBe("USER_SIGNIN_REQUEST");
        expect(USER_SIGNIN_SUCCESS).toBe("USER_SIGNIN_SUCCESS");
        expect(USER_SIGNIN_FAIL).toBe("USER_SIGNIN_FAIL");
        expect(USER_REGISTER_REQUEST).toBe("USER_REGISTER_REQUEST");
        expect(USER_REGISTER_SUCCESS).toBe("USER_REGISTER_SUCCESS");
        expect(USER_REGISTER_FAIL).toBe("USER_REGISTER_FAIL");
        expect(USER_SIGNOUT).toBe("USER_SIGNOUT");
    });
});